# Triangulum Docker Compose Configuration
#
# This file defines the services, networks, and volumes for the Triangulum
# application. It includes the main Triangulum engine, the human review hub,
# Prometheus for metrics collection, and Grafana for metrics visualization.
#
# To start the application, run the following command:
#
# tsh --help
#

version: '3.8'

services:
  # Main Triangulum engine
  engine:
    build:
      context: .
      dockerfile: docker/Dockerfile.engine
    container_name: triangulum-engine
    environment:
      - TRIANGULUM_MODE=auto
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8888:8888"  # API port
      - "8080:8080"  # Dashboard UI port (served by AgenticDashboard in engine)
    command: python -m triangulum_lx.scripts.cli run
    restart: unless-stopped
    networks:
      - triangulum-net

  # Human review hub
  hub:
    build:
      context: .
      dockerfile: docker/Dockerfile.hub
    container_name: triangulum-hub
    depends_on:
      - engine
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./triangulum_data:/app/triangulum_data
    ports:
      - "8000:8000"  # Human hub UI port
    command: python -m triangulum_lx.human.hub
    restart: unless-stopped
    networks:
      - triangulum-net
  
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: triangulum-prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    restart: unless-stopped
    networks:
      - triangulum-net
  
  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: triangulum-grafana
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=triangulum
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - triangulum-net

volumes:
  prometheus-data:
  grafana-data:

networks:
  triangulum-net:
    driver: bridge
